name: divar_app
description: A Flutter app for a Divar-like platform
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^0.69.0
  http: ^1.1.0
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  image: ^4.2.0
  intl: ^0.19.0  #price controller 
  http_parser: ^4.1.2
  cached_network_image: ^3.3.1
  flutter_swiper_null_safety: ^1.0.2  
  jwt_decoder: ^2.0.1
  shamsi_date: ^1.1.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf